# Generated by Django 4.2.1 on 2024-02-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ('-created_at',), 'verbose_name': 'تاریخچه پرداخت', 'verbose_name_plural': 'تاریخچه پرداخت ها'},
        ),
    ]
