# Generated by Django 4.2.1 on 2024-07-05 05:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0016_remove_order_price_after_wallet_withdraw'),
        ('payment', '0004_walletamountsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='type',
            field=models.CharField(default=datetime.datetime(2024, 7, 5, 5, 56, 32, 604831, tzinfo=datetime.timezone.utc), max_length=100, verbose_name='نوع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletamountsession',
            name='desrcription',
            field=models.TextField(default=datetime.datetime(2024, 7, 5, 5, 56, 42, 423005, tzinfo=datetime.timezone.utc), verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletamountsession',
            name='type',
            field=models.CharField(default=datetime.datetime(2024, 7, 5, 5, 56, 48, 594506, tzinfo=datetime.timezone.utc), max_length=100, verbose_name='نوع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AlterField(
            model_name='walletamountsession',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='walletamountsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
