# Generated by Django 4.2.1 on 2024-07-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentsession_type_paymentsession_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletamountsession',
            old_name='desrcription',
            new_name='description',
        ),
    ]
