# Generated by Django 4.2.1 on 2024-02-18 11:25

import accounts.utils
import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ عضویت')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'آقا'), (2, 'خانم')], default=1, verbose_name='جنسیت')),
                ('phone', models.CharField(max_length=11, null=True, unique=True, verbose_name='تلفن همراه')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('valid_phone', models.BooleanField(default=False, verbose_name='تایید تلفن همره')),
                ('valid_email', models.BooleanField(default=False, verbose_name='تایید ایمیل')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('subject', models.CharField(choices=[('phone', 'تلفن همراه'), ('email', 'ایمیل')], max_length=20, verbose_name='نوع کد تایید')),
                ('code', models.CharField(blank=True, default=accounts.utils.generate_new_verification_code, editable=False, max_length=10, unique=True, verbose_name='کد تایید')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'نامعتبر'), (1, 'معتبر'), (2, 'اعمال شده')], default=1, verbose_name='وضعیت کد')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد تایید',
                'verbose_name_plural': 'کدهای تایید',
            },
        ),
    ]
