# Generated by Django 4.2.1 on 2024-07-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_transactionhistory_charge_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='charge_by',
            field=models.CharField(blank=True, choices=[('A', 'ادمین'), ('U', 'کاربر')], default='A', max_length=10, null=True),
        ),
    ]
