# Generated by Django 4.2.1 on 2024-02-18 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='نام داشبورد')),
                ('path', models.CharField(help_text='/panel/', max_length=120, verbose_name='آدرس داشبورد')),
            ],
            options={
                'verbose_name': 'داشبورد',
                'verbose_name_plural': 'داشبوردها',
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('subject', models.CharField(choices=[('phone_verify', 'تایید موبایل'), ('task_expiration', 'کارهای معوق'), ('daily_subtask_expiration', 'یادآور کارهای ناتمام روزانه'), ('project_invite', 'اضافه شدن به پروژه'), ('unreed_comments', 'کامنت\u200cهای نخوانده'), ('teammate_gift', 'هدیه سکه به همکار'), ('reward', 'ثبت پاداش'), ('reward-admin', 'اطلاع ثبت پاداش'), ('new_subtask', 'واگذاری زیرمجموعه کار'), ('birth_date', 'تبریک تولد'), ('other', 'سایر'), ('visa-request', 'درخواست ویزا'), ('visa-request-created-admin', 'ارسال اطلاعیه درخواست ویزا به ادمین')], default='other', max_length=30, verbose_name='موضوع')),
                ('is_sent', models.BooleanField(default=True, verbose_name='وضعیت ارسال')),
                ('status_code', models.PositiveSmallIntegerField(null=True, verbose_name='کد وضعیت')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه اس ام اس',
                'verbose_name_plural': 'تاریخچه اس ام اس ها',
                'ordering': ('-created_at',),
            },
        ),
    ]
