# Generated by Django 4.2.1 on 2024-03-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_smslog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='login_page/', verbose_name='لوگو')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان زیر لوگو')),
                ('description', models.TextField(verbose_name='متن توضیحات')),
            ],
            options={
                'verbose_name': 'بخش ورود',
                'verbose_name_plural': 'بخش ورود',
            },
        ),
    ]
