# Generated by Django 4.2.1 on 2024-03-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_loginpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpage',
            name='description',
            field=models.TextField(default=' برای استفاده از مجموعه های آموزشی زبان سفیر، لطفا شماره موبایل خود را وارد کنید، کد تایید به این شماره پیامک خواهد شد ', verbose_name='متن توضیحات'),
        ),
        migrations.AlterField(
            model_name='loginpage',
            name='title',
            field=models.CharField(default='ورود به حساب کاربری', max_length=200, verbose_name='عنوان زیر لوگو'),
        ),
    ]
