# Generated by Django 4.2.1 on 2024-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_loginpage_description_alter_loginpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpage',
            name='background_image',
            field=models.ImageField(default=1, upload_to='login_page/', verbose_name='عکس پس زمینه'),
            preserve_default=False,
        ),
    ]
