# Generated by Django 4.2.1 on 2024-04-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mainbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='subject',
            field=models.CharField(choices=[('phone_verify', 'تایید موبایل'), ('course_expiration', 'یادآور زمان باقیمانده از مجموعه'), ('unreed_comments', 'کامنت\u200cهای نخوانده'), ('other', 'سایر'), ('visa-request', 'درخواست ویزا'), ('visa-request-created-admin', 'ارسال اطلاعیه درخواست ویزا به ادمین')], default='other', max_length=30, verbose_name='موضوع'),
        ),
    ]
