# Generated by Django 4.2.1 on 2024-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_smslog_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('link', models.CharField(max_length=200, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='main_banner/', verbose_name='عکس لوگو')),
            ],
            options={
                'verbose_name': 'وبسایت',
                'verbose_name_plural': 'وبسایت ها',
            },
        ),
    ]
