# Generated by Django 4.2.1 on 2024-05-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'تاریخچه نوتیفیکیشن ها',
                'verbose_name_plural': 'تاریخچه نوتیفیکیشن ها',
            },
        ),
    ]
