# Generated by Django 4.2.1 on 2024-05-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('success', 'موفق'), ('failure', 'ناموفق')], default=1, max_length=100, verbose_name='وضعیت ارسال'),
            preserve_default=False,
        ),
    ]
