# Generated by Django 4.2.1 on 2024-06-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_notificationlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='link',
            field=models.URLField(default=1, max_length=400, verbose_name='لینک ریدایرکت'),
            preserve_default=False,
        ),
    ]
