# Generated by Django 4.2.1 on 2024-02-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_sent'], 'verbose_name': 'پیام', 'verbose_name_plural': ' پیام\u200cها'},
        ),
    ]
