# Generated by Django 4.2.1 on 2024-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(help_text='پیامتان را بنویسید...', verbose_name='متن پیام'),
        ),
    ]
