# Generated by Django 4.2.1 on 2024-03-10 11:59

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False, verbose_name='خوانده\u200cشده')),
                ('date_sent', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('body', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیام پیشفرض',
                'verbose_name_plural': 'پیام های پیشفرض',
                'ordering': ('date_sent',),
            },
        ),
    ]
