# Generated by Django 4.2.1 on 2024-04-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_defaultmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('index', '-date_created'), 'verbose_name': 'تیکت', 'verbose_name_plural': '  تیکت\u200cها'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ترتیب نمایش'),
        ),
    ]
