# Generated by Django 4.2.1 on 2024-02-18 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_order_price_after_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='order',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='user',
        ),
        migrations.AddField(
            model_name='discount',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_discounts', to='order.order', verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='discount',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
