# Generated by Django 4.2.1 on 2024-02-18 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_remove_discount_order_remove_discount_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='order',
            field=models.ManyToManyField(related_name='order_discounts', to='order.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='user',
            field=models.ManyToManyField(related_name='user_discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
