# Generated by Django 3.2.9 on 2024-02-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_discount_order_alter_discount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_after_discount',
            field=models.PositiveIntegerField(verbose_name='قیمت بعد از تخفیف'),
        ),
    ]
