# Generated by Django 3.2.9 on 2024-02-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_price_after_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_after_discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت بعد از تخفیف'),
        ),
    ]
