# Generated by Django 4.2.1 on 2024-03-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_discount_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='order',
            field=models.ManyToManyField(blank=True, related_name='order_discounts', to='order.order', verbose_name='سفارش'),
        ),
    ]
