# Generated by Django 4.2.1 on 2024-04-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_discount_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('index',), 'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف\u200cها'},
        ),
        migrations.AddField(
            model_name='discount',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ترتیب نمایش'),
        ),
    ]
