# Generated by Django 4.2.1 on 2024-04-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_discount_options_discount_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('index', 'created_at'), 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AddField(
            model_name='order',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ترتیب نمایش'),
        ),
    ]
