# Generated by Django 4.2.1 on 2024-07-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderitem_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_after_wallet_withdraw',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت بعد از برداشت از کیف پول'),
        ),
    ]
