# Generated by Django 4.2.1 on 2024-07-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_price_after_wallet_withdraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_after_wallet_withdraw',
        ),
    ]
