# Generated by Django 4.2.1 on 2024-07-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_part_image_2'),
        ('order', '0016_remove_order_price_after_wallet_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.category'),
        ),
    ]
