# Generated by Django 4.2.1 on 2024-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_part_image_2'),
        ('order', '0017_discount_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='category',
        ),
        migrations.AddField(
            model_name='discount',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='discounts', to='products.category'),
        ),
    ]
