# Generated by Django 4.2.1 on 2024-07-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_remove_discount_category_discount_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='category',
            new_name='categories',
        ),
    ]
