# Generated by Django 4.2.1 on 2024-02-18 11:25

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='پیوند یکتا')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('meta_title', models.CharField(max_length=100, verbose_name='نام کوتاه')),
                ('meta_description', models.TextField(max_length=200, verbose_name='توضیحات کوتاه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدیدها')),
                ('picture', models.ImageField(blank=True, upload_to='category_images/', verbose_name='عکس گروه محصول')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته محصول',
                'verbose_name_plural': 'دسته محصول',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='پیوند یکتا')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('meta_title', models.CharField(max_length=100, verbose_name='نام کوتاه')),
                ('meta_description', models.TextField(max_length=200, verbose_name='توضیحات کوتاه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدیدها')),
                ('image', models.ImageField(upload_to='chapter_images/', verbose_name='عکس')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'لیست فصل ها',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, verbose_name='نام')),
                ('last_name', models.CharField(max_length=300, verbose_name='نام خانوادگی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='پیوند یکتا')),
                ('phone', models.CharField(max_length=11, null=True, unique=True, verbose_name='تلفن همراه')),
                ('image', models.ImageField(upload_to='professor_images/', verbose_name='عکس')),
                ('specialty', models.CharField(blank=True, max_length=500, null=True, verbose_name='تخصص ها')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدیدها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='پیوند یکتا')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('meta_title', models.CharField(max_length=100, verbose_name='نام کوتاه')),
                ('meta_description', models.TextField(max_length=200, verbose_name='توضیحات کوتاه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدیدها')),
                ('image', models.ImageField(upload_to='part_images/', verbose_name='عکس')),
                ('video_link', models.URLField(verbose_name='لینک ویدیو')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='products.chapter', verbose_name='فصل مربوطه')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'لیست محصول',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='پیوند یکتا')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('meta_title', models.CharField(max_length=100, verbose_name='نام کوتاه')),
                ('meta_description', models.TextField(max_length=200, verbose_name='توضیحات کوتاه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدیدها')),
                ('image', models.ImageField(upload_to='package_images/', verbose_name='عکس')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('categories', models.ManyToManyField(related_name='packages', to='products.category', verbose_name='دسته\u200cها')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'لیست دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='پیوند یکتا')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('meta_title', models.CharField(max_length=100, verbose_name='نام کوتاه')),
                ('meta_description', models.TextField(max_length=200, verbose_name='توضیحات کوتاه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدیدها')),
                ('image', models.ImageField(upload_to='course_images/', verbose_name='عکس')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='products.package', verbose_name='دسته بندی مربوطه')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='products.professor', verbose_name='استاد مجموعه')),
            ],
            options={
                'verbose_name': 'مجموعه',
                'verbose_name_plural': 'لیست مجموعه',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_comments', to='products.course', verbose_name='مجموعه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'لیست نظرات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='products.course', verbose_name='مجموعه مربوطه'),
        ),
    ]
