# Generated by Django 4.2.1 on 2024-02-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='video_link',
            field=models.TextField(verbose_name='لینک ویدیو'),
        ),
    ]
