# Generated by Django 4.2.1 on 2024-02-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_part_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='price',
        ),
        migrations.RemoveField(
            model_name='part',
            name='price',
        ),
    ]
