# Generated by Django 4.2.1 on 2024-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_chapter_price_remove_part_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('-part_index',), 'verbose_name': 'محصول', 'verbose_name_plural': 'لیست محصول'},
        ),
        migrations.AddField(
            model_name='part',
            name='part_index',
            field=models.IntegerField(default=1, verbose_name='شماره محصول'),
            preserve_default=False,
        ),
    ]
