# Generated by Django 4.2.1 on 2024-03-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_part_options_part_part_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_time',
            field=models.CharField(default=1, max_length=100, verbose_name='زمان ویدئو'),
            preserve_default=False,
        ),
    ]
