# Generated by Django 4.2.1 on 2024-03-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_part_part_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('part_index',), 'verbose_name': 'محصول', 'verbose_name_plural': 'لیست محصول'},
        ),
    ]
