# Generated by Django 4.2.1 on 2024-03-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_part_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pre_video',
            field=models.TextField(default=1, verbose_name='لینک ویدیوی پیش نمایش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='pre_video',
            field=models.TextField(default=1, verbose_name='لینک ویدیوی پیش نمایش'),
            preserve_default=False,
        ),
    ]
