# Generated by Django 4.2.1 on 2024-03-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='products.course', verbose_name='مجموعه مربوطه'),
        ),
        migrations.AlterField(
            model_name='part',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='products.chapter', verbose_name='فصل مربوطه'),
        ),
    ]
