# Generated by Django 4.2.1 on 2024-03-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_chapter_course_alter_part_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='views',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='views',
        ),
        migrations.RemoveField(
            model_name='course',
            name='views',
        ),
        migrations.RemoveField(
            model_name='package',
            name='views',
        ),
        migrations.RemoveField(
            model_name='part',
            name='views',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='views',
        ),
        migrations.AddField(
            model_name='category',
            name='student_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجو'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='student_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجو'),
        ),
        migrations.AddField(
            model_name='course',
            name='student_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجو'),
        ),
        migrations.AddField(
            model_name='package',
            name='student_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجو'),
        ),
        migrations.AddField(
            model_name='part',
            name='student_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجو'),
        ),
        migrations.AddField(
            model_name='professor',
            name='student_count',
            field=models.PositiveIntegerField(default=0, verbose_name='دانشجوها'),
        ),
    ]
