# Generated by Django 4.2.1 on 2024-03-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_course_day_limit_package_day_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='products.course', verbose_name='مجموعه مربوطه'),
        ),
    ]
