# Generated by Django 4.2.1 on 2024-03-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_professor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='packages', to='products.category', verbose_name='دسته\u200cها'),
        ),
    ]
