# Generated by Django 4.2.1 on 2024-04-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_course_categories_alter_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='course',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='package',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='part',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ترتیب نمایش'),
        ),
    ]
