# Generated by Django 4.2.1 on 2024-04-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_category_index_chapter_index_course_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('index',), 'verbose_name': 'فصل', 'verbose_name_plural': 'لیست فصل ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('index',), 'verbose_name': 'نظر', 'verbose_name_plural': 'لیست نظرات'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('index',), 'verbose_name': 'مجموعه', 'verbose_name_plural': 'لیست مجموعه'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('index',), 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'لیست دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('index',), 'verbose_name': 'محصول', 'verbose_name_plural': 'لیست محصول'},
        ),
        migrations.AddField(
            model_name='comment',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ترتیب نمایش'),
        ),
    ]
