# Generated by Django 4.2.1 on 2024-04-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_chapter_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('index',), 'verbose_name': 'دسته محصول', 'verbose_name_plural': 'دسته محصول'},
        ),
    ]
