# Generated by Django 4.2.1 on 2024-05-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='products.category', verbose_name='دسته بندی مربوطه'),
        ),
    ]
