# Generated by Django 4.2.1 on 2024-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_part_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
