# Generated by Django 4.2.1 on 2024-05-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_part_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_with_discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AddField(
            model_name='package',
            name='price_with_discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AddField(
            model_name='part',
            name='price_with_discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف'),
        ),
    ]
