# Generated by Django 4.2.1 on 2024-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_course_price_with_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(max_length=500, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(max_length=500, verbose_name='نام کوتاه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=500, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='meta_description',
            field=models.TextField(max_length=500, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='meta_title',
            field=models.CharField(max_length=500, verbose_name='نام کوتاه'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=500, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_description',
            field=models.TextField(max_length=500, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_title',
            field=models.CharField(max_length=500, verbose_name='نام کوتاه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='package',
            name='meta_description',
            field=models.TextField(max_length=500, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='package',
            name='meta_title',
            field=models.CharField(max_length=500, verbose_name='نام کوتاه'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=500, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='part',
            name='meta_description',
            field=models.TextField(max_length=500, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='part',
            name='meta_title',
            field=models.CharField(max_length=500, verbose_name='نام کوتاه'),
        ),
        migrations.AlterField(
            model_name='part',
            name='title',
            field=models.CharField(max_length=500, verbose_name='نام'),
        ),
    ]
