# Generated by Django 4.2.1 on 2024-06-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='part/images/', verbose_name='عکس دوم(سایز مستطیلی)'),
        ),
    ]
